import {VisualEffectEngine} from '../src/effects.js';
import {defaults,FX} from '../src/core.js';
import {RecognitionEngine} from '../src/recognition.js';
import {loadImage} from '../src/search.js';
import * as store from '../src/storage.js';
import {CaptureEngine} from '../src/capture.js';
const out=document.querySelector('#results'),sample=document.querySelector('#sample'),ctx=sample.getContext('2d');
function pattern(){for(let y=0;y<72;y++)for(let x=0;x<128;x++){ctx.fillStyle=`rgb(${x*2},${y*3},${x%16<8?40:220})`;ctx.fillRect(x,y,1,1);}}
function pixels(source){const c=document.createElement('canvas');c.width=128;c.height=72;c.getContext('2d').drawImage(source,0,0,128,72);return c.getContext('2d').getImageData(0,0,128,72).data;}
const log=s=>out.textContent+='\n'+s;
document.querySelector('#run').onclick=async()=>{out.textContent='Browser: '+navigator.userAgent;let failures=0;const check=(v,s)=>{log(`${v?'PASS':'FAIL'} ${s}`);if(!v)failures++;};pattern();const original=pixels(sample),engine=new VisualEffectEngine();log('Renderer: '+engine.backend);for(const n of FX){const s=defaults();s.fx[n].on=true;engine.reset();let result=pixels(engine.apply(sample,s.fx));if(n==='echo'){ctx.fillStyle='red';ctx.fillRect(0,0,128,72);result=pixels(engine.apply(sample,s.fx));check(result.some((v,i)=>v!==pixels(sample)[i]),'echo stores temporal frame');pattern();}else check(result.some((v,i)=>v!==original[i]),n+' changes pixels');}const s=defaults();FX.forEach(n=>s.fx[n].on=true);check(pixels(engine.apply(sample,s.fx)).length===128*72*4,'six FX simultaneous');await store.save('__qa__',{seed:'fixed',blob:new Blob(['video fixture'])});const restored=await store.read('__qa__');check(restored.seed==='fixed'&&await restored.blob.text()==='video fixture','IndexedDB settings and Blob roundtrip');check(document.documentElement.scrollWidth<=innerWidth,'layout no horizontal overflow');log(`DONE: ${failures} failures`);};
document.querySelector('#ai').onclick=async()=>{out.textContent='Loading actual MediaPipe model...';try{const r=new RecognitionEngine();await r.init();log('PASS model initialized in worker');const image=await loadImage('../public/assets/bus-0.jpg');const bitmap=await createImageBitmap(image);const result=await r.call({type:'detect',bitmap},[bitmap]);log('Actual detections: '+JSON.stringify(result.detections.map(d=>({category:d.categories[0].categoryName,score:d.categories[0].score}))));log('DONE: actual model invocation succeeded (accuracy not certified)');r.worker.terminate();}catch(e){log('FAIL '+e.message);}};
const mediaButton=document.createElement('button');mediaButton.textContent='Test synthetic recording and video analysis';document.body.append(mediaButton);
mediaButton.onclick=async()=>{out.textContent='Synthetic fixture test — no real camera';let engine,rec;
try{const fixture=document.createElement('canvas');fixture.width=640;fixture.height=360;const image=await loadImage('../public/assets/bus-0.jpg');const draw=()=>fixture.getContext('2d').drawImage(image,0,0,640,360);draw();const preview=document.createElement('video');preview.muted=true;preview.playsInline=true;rec=new CaptureEngine(preview);rec.stream=fixture.captureStream(15);const timer=setInterval(draw,66);const blob=await new Promise(resolve=>rec.record(2,()=>{},resolve));clearInterval(timer);rec.close();if(!blob.size)throw Error('Empty recording');log('PASS CaptureEngine MediaRecorder: '+blob.size+' bytes');preview.src=URL.createObjectURL(blob);await new Promise((resolve,reject)=>{preview.onloadedmetadata=resolve;preview.onerror=reject;});if(!Number.isFinite(preview.duration)){preview.currentTime=1e9;await new Promise(r=>preview.addEventListener('timeupdate',r,{once:true}));preview.currentTime=0;}log('PASS video metadata duration: '+preview.duration.toFixed(3));engine=new RecognitionEngine();const tracks=await engine.analyze(preview,1,()=>{});log('PASS recorded-video analysis: '+tracks.length+' tracks, '+tracks.reduce((s,t)=>s+t.trajectory.length,0)+' observations');if(!tracks.some(t=>t.category==='bus'&&t.trajectory.length>=2))throw Error('Bus ID not maintained in sample');log('PASS same bus tracked over multiple frames');const p={version:1,id:'qa-synthetic-video',title:'QA SYNTHETIC BUS / NOT A REAL WALK',duration:preview.duration,source:'video',tracks,candidates:[],settings:defaults()};await store.save('qa-fixture',p);log('DONE: synthetic recording and analysis passed (physical camera remains untested)');}catch(e){log('FAIL '+e.message);}finally{rec?.dispose();engine?.worker?.terminate();}};
