export class CaptureEngine{
 constructor(video){this.video=video;this.stream=null;this.recorder=null;this.samples=[];this.orientationHandler=null;}
 async cameras(){return(await navigator.mediaDevices.enumerateDevices()).filter(x=>x.kind==='videoinput');}
 async open({facing='environment',deviceId,frameRate=30}={}){this.close();if(!navigator.mediaDevices?.getUserMedia)throw Error('このブラウザーではカメラを利用できません。HTTPSまたは動画ファイルを使用してください');this.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{...(deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:facing}}),width:{ideal:1280},height:{ideal:720},frameRate:{ideal:frameRate,max:frameRate}}});this.video.srcObject=this.stream;this.video.muted=true;await this.video.play();return this.cameras();}
 record(seconds,onTick,onDone){if(!this.stream)throw Error('先にカメラを起動してください');if(!globalThis.MediaRecorder)throw Error('録画非対応です。端末のカメラで撮影した動画を読み込んでください');const mime=['video/mp4','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));this.chunks=[];this.samples=[];this.started=performance.now();this.recorder=new MediaRecorder(this.stream,mime?{mimeType:mime}:undefined);this.recorder.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data);};this.recorder.onstop=()=>{clearInterval(this.timer);onDone(new Blob(this.chunks,{type:this.recorder.mimeType}),Math.min(seconds,(performance.now()-this.started)/1000),this.samples);};this.recorder.start(1000);onTick(seconds);this.timer=setInterval(()=>{const left=Math.max(0,seconds-(performance.now()-this.started)/1000);onTick(left);if(!left)this.stop();},200);}
 stop(){if(this.recorder?.state==='recording')this.recorder.stop();clearInterval(this.timer);}
 close(){this.stop();this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;if(this.video)this.video.srcObject=null;}
 async gps(){if(!navigator.geolocation)throw Error('GPS非対応です');if(this.watch!=null)return;this.watch=navigator.geolocation.watchPosition(p=>this.samples.push({type:'gps',time:this.elapsed(),lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),e=>this.onSensorError?.(e),{enableHighAccuracy:true});}
 elapsed(){return this.recorder?.state==='recording'?(performance.now()-this.started)/1000:0;}
 async orientation(){if(!globalThis.DeviceOrientationEvent)throw Error('姿勢センサー非対応です');if(DeviceOrientationEvent.requestPermission&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error('姿勢センサーの利用が許可されませんでした');if(this.orientationHandler)return;let last=0;this.orientationHandler=e=>{if(performance.now()-last<200)return;last=performance.now();this.samples.push({type:'orientation',time:this.elapsed(),alpha:e.alpha,beta:e.beta,gamma:e.gamma});};window.addEventListener('deviceorientation',this.orientationHandler);}
 dispose(){this.close();if(this.watch!=null)navigator.geolocation.clearWatch(this.watch);this.watch=null;if(this.orientationHandler)window.removeEventListener('deviceorientation',this.orientationHandler);this.orientationHandler=null;}
}
