import {FX} from './core.js';
// Fixed order: MOSAIC → NEGATIVE → THRESHOLD → EDGE → RGB SHIFT → ECHO.
const vertex=`attribute vec2 p;varying vec2 uv;void main(){uv=(p+1.0)*0.5;gl_Position=vec4(p,0.,1.);}`;
const fragment=`precision mediump float;varying vec2 uv;uniform sampler2D frame;uniform sampler2D history;uniform vec2 size;uniform float negative,mosaic,threshold,edge,rgb,echo;uniform bool binaryOn;
vec4 base(vec2 q){if(mosaic>1.)q=(floor(q*size/mosaic)+.5)*mosaic/size;vec4 c=texture2D(frame,clamp(q,vec2(0.),vec2(1.)));c.rgb=mix(c.rgb,1.-c.rgb,negative);if(binaryOn)c.rgb=vec3(step(threshold,dot(c.rgb,vec3(.299,.587,.114))));return c;}
vec4 outlined(vec2 q){vec4 c=base(q);if(edge>0.){vec2 d=1./size;vec3 x=base(q+vec2(d.x,0.)).rgb-base(q-vec2(d.x,0.)).rgb;vec3 y=base(q+vec2(0.,d.y)).rgb-base(q-vec2(0.,d.y)).rgb;c.rgb=mix(c.rgb,clamp(sqrt(x*x+y*y)*3.,0.,1.),edge);}return c;}
void main(){vec4 c=outlined(uv);if(rgb>0.){c.r=outlined(uv+vec2(rgb/size.x,0.)).r;c.b=outlined(uv-vec2(rgb/size.x,0.)).b;}vec4 old=texture2D(history,uv);gl_FragColor=mix(c,old,echo);}`;
export class VisualEffectEngine{
 constructor(){this.canvas=document.createElement('canvas');this.gl=this.canvas.getContext('webgl',{alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true});if(this.gl){try{this.init();this.backend='WebGL';}catch{this.gl=null;this.canvas=document.createElement('canvas');}}if(!this.gl){this.ctx=this.canvas.getContext('2d',{willReadFrequently:true});this.backend='CPU / 640px';}}
 init(){const g=this.gl;const shader=(type,source)=>{const s=g.createShader(type);g.shaderSource(s,source);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(s));return s;};const p=g.createProgram();g.attachShader(p,shader(g.VERTEX_SHADER,vertex));g.attachShader(p,shader(g.FRAGMENT_SHADER,fragment));g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));g.useProgram(p);this.program=p;const b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),g.STATIC_DRAW);const a=g.getAttribLocation(p,'p');g.enableVertexAttribArray(a);g.vertexAttribPointer(a,2,g.FLOAT,false,0,0);this.textures=[0,1].map(unit=>{g.activeTexture(g.TEXTURE0+unit);const t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);return t;});g.uniform1i(g.getUniformLocation(p,'frame'),0);g.uniform1i(g.getUniformLocation(p,'history'),1);}
 reset(){this.dirty=true;this.previous=null;}
 apply(source,fx,dt=1/30,decay=.8){if(!FX.some(n=>fx[n].on)){this.reset();return source;}const g=this.gl;const w=g?source.width:Math.min(640,source.width),h=Math.round(source.height*w/source.width);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.dirty=true;this.previous=null;}const v=n=>fx[n].on?fx[n].value:0;const retention=fx.echo.on?Math.pow(Math.min(.98,v('echo')),dt/Math.max(.05,decay)):0;
 if(g){g.viewport(0,0,w,h);g.useProgram(this.program);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.textures[0]);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,true);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,source);g.activeTexture(g.TEXTURE1);g.bindTexture(g.TEXTURE_2D,this.textures[1]);if(this.dirty){g.texImage2D(g.TEXTURE_2D,0,g.RGBA,w,h,0,g.RGBA,g.UNSIGNED_BYTE,null);this.dirty=false;}g.uniform2f(g.getUniformLocation(this.program,'size'),w,h);for(const n of ['negative','mosaic','threshold','edge','rgb'])g.uniform1f(g.getUniformLocation(this.program,n),v(n));g.uniform1f(g.getUniformLocation(this.program,'echo'),this.hasFrame?retention:0);g.uniform1i(g.getUniformLocation(this.program,'binaryOn'),fx.threshold.on);g.drawArrays(g.TRIANGLES,0,6);g.copyTexImage2D(g.TEXTURE_2D,0,g.RGBA,0,0,w,h,0);this.hasFrame=true;}
 else{const c=this.ctx;c.clearRect(0,0,w,h);const size=Math.max(1,v('mosaic'));if(size>1){const small=document.createElement('canvas');small.width=Math.max(1,Math.round(w/size));small.height=Math.max(1,Math.round(h/size));small.getContext('2d').drawImage(source,0,0,small.width,small.height);c.imageSmoothingEnabled=false;c.drawImage(small,0,0,w,h);}else c.drawImage(source,0,0,w,h);const img=c.getImageData(0,0,w,h),p=img.data;for(let i=0;i<p.length;i+=4){for(let k=0;k<3;k++)p[i+k]=p[i+k]*(1-v('negative'))+(255-p[i+k])*v('negative');if(fx.threshold.on){const l=(.299*p[i]+.587*p[i+1]+.114*p[i+2])/255;for(let k=0;k<3;k++)p[i+k]=l>=v('threshold')?255:0;}}
 if(fx.edge.on){const a=new Uint8ClampedArray(p);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;for(let k=0;k<3;k++){const dx=a[i+4+k]-a[i-4+k],dy=a[i+w*4+k]-a[i-w*4+k];p[i+k]=a[i+k]*(1-v('edge'))+Math.min(255,Math.hypot(dx,dy)*3)*v('edge');}}}
 if(fx.rgb.on){const a=new Uint8ClampedArray(p),shift=Math.round(v('rgb'));for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;p[i]=a[(y*w+Math.min(w-1,x+shift))*4];p[i+2]=a[(y*w+Math.max(0,x-shift))*4+2];}}
 if(this.previous?.length===p.length&&retention)for(let i=0;i<p.length;i++)p[i]=p[i]*(1-retention)+this.previous[i]*retention;this.previous=new Uint8ClampedArray(p);c.putImageData(img,0,0);}return this.canvas;}
}
