import {enrich} from './search.js';

const presets=['Tokyo walking','Shibuya street','Tokyo traffic','New York street','London walking','Urban landscape'];
const style=`.online-video{display:none;margin:0 0 24px}.online-video.active{display:block}.online-search{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.online-search input{flex:1;min-width:220px}.online-presets{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:18px}.online-presets button{font-size:11px}.online-results{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:14px}.online-card{border:1px solid var(--line);background:var(--panel);padding:10px}.online-card.selected{border-color:var(--acid)}.online-card img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover;background:#080b08}.online-card h3{font:500 18px var(--heading);margin:10px 0 5px}.online-card p{font-size:11px;line-height:1.5;color:var(--muted);margin:4px 0}.online-card button{width:100%;margin-top:8px}.online-preview{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:20px;margin-top:22px;padding-top:20px;border-top:1px solid var(--line)}.online-preview video{width:100%;aspect-ratio:16/9;background:#050705}.online-controls label{margin:9px 0}.online-progress{margin-top:18px}.online-progress ol{padding-left:24px;color:var(--muted);font-size:12px;line-height:2}.online-progress li.done{color:var(--acid)}.online-error{color:#ffb976}.library-list{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}@media(max-width:850px){.online-preview{grid-template-columns:1fr}.online-results{grid-template-columns:repeat(2,minmax(0,1fr))}}`;
function el(tag, text, cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
function clean(s){return String(s||'').replace(/<[^>]*>/g,'').replace(/&[^;]+;/g,' ').trim();}
function apiSearch(query,offset=0){const p=new URLSearchParams({action:'query',generator:'search',gsrsearch:`${query} filetype:video`,gsrnamespace:'6',gsrlimit:'12',gsroffset:String(offset),prop:'imageinfo',iiprop:'url|mime|size|mediatype|extmetadata',iiurlwidth:'480',format:'json',origin:'*'});return fetch(`https://commons.wikimedia.org/w/api.php?${p}`).then(async r=>{if(!r.ok)throw Error(`Commons検索エラー (${r.status})`);const j=await r.json();if(j.error)throw Error(j.error.info);return j;});}
function normalise(data){return Object.values(data.query?.pages||{}).flatMap(page=>{const info=page.imageinfo?.[0],meta=info?.extmetadata||{};if(!info||info.mediatype!=='VIDEO'||!String(info.mime||'').startsWith('video/'))return[];return[{id:String(page.pageid),title:page.title.replace(/^File:/,''),url:info.url,thumbnail:info.thumburl||'',mime:info.mime||'unknown',size:info.size||null,sourceUrl:info.descriptionurl||'',license:clean(meta.LicenseShortName?.value)||'権利情報不明',licenseUrl:meta.LicenseUrl?.value||'',author:clean(meta.Artist?.value)||'作者情報不明',credit:clean(meta.Credit?.value),duration:clean(meta.Duration?.value)||'不明',themes:[]}];});}
export function initOnlineVideo({tab,video,project,setProject,recognition,provider,saveProject,renderArchive,showArchive,showExhibition,toast,status,seek,loadDemo,setSettings}){
 document.head.append(Object.assign(document.createElement('style'),{textContent:style}));
 document.head.append(Object.assign(document.createElement('style'),{textContent:'.capture-tabs{display:flex;gap:8px;border-bottom:1px solid var(--line);margin-bottom:18px}.capture-tab{font-size:11px}.capture-tab.active{color:var(--acid);border-color:var(--acid)}'}));
 let existingTabs=document.querySelector('.capture-tabs');if(!existingTabs){existingTabs=document.createElement('div');existingTabs.className='capture-tabs';existingTabs.setAttribute('role','tablist');document.querySelector('#capture .capture-grid')?.before(existingTabs);}
 const capture=document.querySelector('#capture');if(!capture)return;const panel=document.createElement('section');panel.className='online-video';panel.innerHTML=`<div class="section-heading"><div><p class="eyebrow">ONLINE VIDEO / COMMONS</p><h2>ネット上の街歩きを再構築する。</h2></div><button type="button" data-online-reset>LOCAL DEMOへ戻る</button></div><div class="online-search"><input data-online-query aria-label="動画検索キーワード" value="Tokyo walking" maxlength="160"><button type="button" class="primary" data-online-search>SEARCH VIDEOS</button><button type="button" data-online-more disabled>MORE 12</button></div><div class="online-presets"></div><p class="hint">Wikimedia Commonsの動画だけを検索します。タイトルから歩行視点だと断定せず、プレビューで選択してください。動画URL、作者、ライセンス、出典を保持します。再生・Canvas解析がCORSや形式で失敗する場合は、提供元から手動でダウンロードしてLOCAL VIDEOに読み込んでください。</p><div class="online-results"></div><div class="online-preview"><div><video data-online-preview playsinline controls muted crossorigin="anonymous"></video><p data-online-meta class="hint">動画を選択してください。</p></div><div class="online-controls"><label>解析区間<select data-online-length><option value="30">30秒</option><option value="60">60秒</option><option value="120" selected>120秒</option><option value="300">300秒</option></select></label><label>開始位置（秒）<input data-online-start type="number" min="0" step="0.1" value="0"></label><label>解析頻度<select data-online-hz><option value="0.5">0.5 FPS</option><option value="1" selected>1 FPS</option><option value="2">2 FPS</option><option value="5">5 FPS</option></select></label><button type="button" class="primary" data-online-analyze disabled>ANALYZE &amp; RECONSTRUCT</button><div class="online-progress"><progress data-online-progress value="0" max="1"></progress><ol data-online-steps><li>動画を選択</li><li>読み込み・CORS確認</li><li>MediaPipe検出・追跡</li><li>代表画像抽出</li><li>Commons画像検索</li><li>IMAGE ARCHIVE登録</li><li>EXHIBITION上映</li></ol></div></div></div><details><summary>DEMO VIDEO LIBRARY（検索済み素材のみ）</summary><p class="hint">架空のURLは登録しません。検索結果から選択した実在動画だけがこの端末のライブラリに保存されます。</p><div class="library-list" data-online-library></div></details>`;capture.append(panel);const tabs=document.querySelector('.capture-tabs');if(tabs){for(const [id,label] of [['camera','CAMERA'],['local','LOCAL VIDEO'],['online','ONLINE VIDEO']]){if(!tabs.querySelector(`[data-capture-tab="${id}"]`)){const b=el('button',label,'capture-tab');b.dataset.captureTab=id;tabs.append(b);}}}
 const results=panel.querySelector('.online-results'),query=panel.querySelector('[data-online-query]'),more=panel.querySelector('[data-online-more]'),preview=panel.querySelector('[data-online-preview]'),meta=panel.querySelector('[data-online-meta]'),analyze=panel.querySelector('[data-online-analyze]'),progress=panel.querySelector('[data-online-progress]'),steps=[...panel.querySelectorAll('[data-online-steps] li')],length=panel.querySelector('[data-online-length]'),start=panel.querySelector('[data-online-start]'),library=panel.querySelector('[data-online-library]');let found=[],offset=0,selected=null,searching=false;
 const showTab=id=>{panel.classList.toggle('active',id==='online');document.querySelectorAll('.capture-tab').forEach(b=>b.classList.toggle('active',b.dataset.captureTab===id));if(id==='camera'){document.querySelectorAll('#capture > .capture-grid').forEach(x=>x.style.display='grid');}else if(id==='local'){document.querySelectorAll('#capture > .capture-grid').forEach(x=>x.style.display='grid');}else document.querySelectorAll('#capture > .capture-grid').forEach(x=>x.style.display='none');};
 document.querySelectorAll('.capture-tab').forEach(b=>b.onclick=()=>showTab(b.dataset.captureTab));
 const setStep=(i,done=true)=>{if(steps[i])steps[i].classList.toggle('done',done);};
 const draw=()=>{results.replaceChildren();if(!found.length){results.append(el('p','検索結果はここに表示されます。','empty'));return;}for(const item of found){const card=el('article',null,`online-card ${selected?.id===item.id?'selected':''}`);const img=el('img');img.src=item.thumbnail;img.alt=item.title;img.loading='lazy';card.append(img,el('h3',item.title),el('p',`${item.mime} · ${item.duration} · ${item.size?Math.round(item.size/1048576)+' MB':'サイズ不明'}`),el('p',`${item.license} · ${item.author}`));const a=el('a','出典 ↗');a.href=item.sourceUrl||'#';a.target='_blank';a.rel='noopener';card.append(a);const b=el('button',selected?.id===item.id?'選択中':'PREVIEW');b.onclick=()=>select(item);card.append(b);results.append(card);}};
 const select=item=>{selected=item;preview.crossOrigin='anonymous';preview.src=item.url;preview.load();meta.textContent=`${item.title} / ${item.license} / ${item.author} · 出典: ${item.sourceUrl}`;analyze.disabled=false;draw();setStep(0);};
 async function search(){if(searching)return;searching=true;more.disabled=true;status('SEARCHING ONLINE VIDEO');try{const data=await apiSearch(query.value.trim()||'Tokyo walking',offset);const next=normalise(data);found=offset?found.concat(next):next;offset+=12;more.disabled=!data.continue;draw();if(!found.length)toast('対応するWebM/MP4動画が見つかりませんでした。画像結果は除外しています。');}catch(e){toast(e.message);results.replaceChildren(el('p',`検索に失敗しました: ${e.message}`,'online-error'));}finally{searching=false;status('READY');}};
 panel.querySelector('[data-online-search]').onclick=search;more.onclick=search;query.onkeydown=e=>{if(e.key==='Enter')search();};
 presets.forEach(text=>{const b=el('button',text);b.onclick=()=>{query.value=text;offset=0;found=[];search();};panel.querySelector('.online-presets').append(b);});
 panel.querySelector('[data-online-reset]').onclick=()=>loadDemo();
 length.onchange=()=>{if(selected&&Number.isFinite(preview.duration))length.value=String(Math.min(+length.value,Math.max(1,Math.floor(preview.duration))));};
 analyze.onclick=async()=>{if(!selected)return;analyze.disabled=true;progress.value=0;steps.forEach(x=>x.classList.remove('done'));status('ONLINE ANALYZING');try{setStep(0);setStep(1);await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('動画の読み込みがタイムアウトしました。CORSまたは形式を確認してください')),15000);const done=()=>{clearTimeout(timer);preview.removeEventListener('loadedmetadata',done);preview.removeEventListener('error',bad);resolve();};const bad=()=>{clearTimeout(timer);preview.removeEventListener('loadedmetadata',done);preview.removeEventListener('error',bad);reject(Error('ブラウザーで再生できない動画です。ダウンロード後にLOCAL VIDEOを使用してください'));};if(preview.readyState>=1)done();else{preview.addEventListener('loadedmetadata',done);preview.addEventListener('error',bad);preview.load();}});const actual=Math.min(+length.value,Math.floor(preview.duration));const begin=Math.max(0,Math.min(+start.value||0,Math.max(0,preview.duration-.1)));const end=Math.min(preview.duration,begin+actual);setStep(2);const tracks=await recognition.analyze(preview,+panel.querySelector('[data-online-hz]').value,(p,t)=>{progress.value=p;status(`ONLINE ANALYZING ${Math.round(p*100)}% · ${t.length} objects`);},undefined,{start:begin,end});setStep(3);const next={version:1,id:crypto.randomUUID(),title:selected.title,duration:end-begin,source:'online',sourceUrl:selected.sourceUrl,media:{url:selected.url,mime:selected.mime,license:selected.license,author:selected.author},tracks,candidates:[],sensors:[]};setProject(next);setStep(4);for(const track of tracks){try{const candidates=await provider.search(track,track.category);await enrich(candidates,track,new Map());next.candidates.push(...candidates.slice(0,10));}catch{}}setStep(5);if(setSettings)setSettings(next.duration);await saveProject();library.append(el('button',selected.title));setStep(6);showArchive();showExhibition();toast(`解析完了: ${tracks.length} objects / ${next.candidates.length} images`);}catch(e){toast(e.message);status('ONLINE VIDEO ERROR');}finally{analyze.disabled=false;}};
 showTab('online');search();
}
