import {Tracker} from './core.js';
import {features} from './search.js';
export class RecognitionEngine{
 constructor(){this.next=0;this.pending=new Map();}
 async init(){if(this.ready)return;this.worker=new Worker(new URL('./recognition-worker.js',import.meta.url));this.worker.onmessage=({data})=>{const p=this.pending.get(data.id);if(!p)return;clearTimeout(p.timer);this.pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data);};this.worker.onerror=e=>{for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error(e.message||'AIワーカーを起動できません'));}this.pending.clear();};try{await this.call({type:'init'});this.ready=true;}catch(e){this.worker.terminate();throw e;}}
 call(data,transfer=[]){return new Promise((resolve,reject)=>{const id=++this.next;const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('AI処理がタイムアウトしました。デモまたは手動指定を使用できます'));},90000);this.pending.set(id,{resolve,reject,timer});this.worker.postMessage({...data,id},transfer);});}
 async detect(video){const w=video.videoWidth,h=video.videoHeight;if(!w||!h)return[];const bitmap=await createImageBitmap(video);const r=await this.call({type:'detect',bitmap},[bitmap]);return r.detections.map(d=>({category:d.categories[0].categoryName,confidence:d.categories[0].score,box:[d.boundingBox.originX/w,d.boundingBox.originY/h,d.boundingBox.width/w,d.boundingBox.height/h].map(v=>Math.max(0,Math.min(1,v)))}));}
 async analyze(video,hz,onProgress,signal){await this.init();const duration=video.duration;if(!Number.isFinite(duration)||duration<=0)throw Error('動画の長さを取得できません。別形式で保存してください');const tracker=new Tracker(Math.max(1.5,2/hz));video.pause();const original=video.currentTime;
 try{for(let t=0;t<duration;t+=1/hz){if(signal?.aborted)throw new DOMException('解析を中断しました','AbortError');await seek(video,Math.min(t,duration-.01));const detections=await this.detect(video);for(const d of detections){const c=document.createElement('canvas');c.width=160;c.height=120;const b=d.box;try{c.getContext('2d').drawImage(video,b[0]*video.videoWidth,b[1]*video.videoHeight,b[2]*video.videoWidth,b[3]*video.videoHeight,0,0,160,120);d.representative=c.toDataURL('image/jpeg',.65);d.features=features(c);}catch{}}tracker.update(detections,t);onProgress(t/duration,tracker.tracks);await new Promise(r=>setTimeout(r,0));}for(const t of tracker.tracks)t.end=Math.min(duration,t.end+1/hz);return tracker.tracks;}finally{await seek(video,Math.min(original,duration-.01));}}
}
export function seek(video,time){return new Promise((resolve,reject)=>{if(Math.abs(video.currentTime-time)<.015&&video.readyState>=2)return resolve();const timer=setTimeout(()=>{clean();reject(Error('動画シークのタイムアウト'));},10000);const clean=()=>{clearTimeout(timer);video.removeEventListener('seeked',done);video.removeEventListener('error',bad);};const done=()=>{clean();resolve();};const bad=()=>{clean();reject(Error('動画をデコードできません'));};video.addEventListener('seeked',done);video.addEventListener('error',bad);video.currentTime=time;});}

