import {boxAt,clamp,effectiveFX} from './core.js';
import {VisualEffectEngine} from './effects.js';
const canvas=()=>document.createElement('canvas');
export class ReconstructionEngine{
 constructor(output,cache){this.output=output;this.ctx=output.getContext('2d');this.cache=cache;this.real=canvas();this.virtual=canvas();this.objects=canvas();this.effects=[new VisualEffectEngine(),new VisualEffectEngine(),new VisualEffectEngine()];}
 resize(w){const h=Math.round(w*9/16);for(const c of [this.output,this.real,this.virtual,this.objects])if(c.width!==w||c.height!==h){c.width=w;c.height=h;}}
 reset(){this.effects.forEach(f=>f.reset());}
 draw({project,settings:s,video,time,loop,world,oldWorld,transitionAge,dt}){this.resize(s.resolution);const w=this.output.width,h=this.output.height;const r=this.real.getContext('2d'),v=this.virtual.getContext('2d'),o=this.objects.getContext('2d');r.fillStyle='#101b20';r.fillRect(0,0,w,h);o.clearRect(0,0,w,h);v.fillStyle='#101618';v.fillRect(0,0,w,h);
 if(video?.readyState>=2)r.drawImage(video,0,0,w,h);else if(project.source==='demo'){const t=project.tracks[0],c=project.candidates.find(c=>c.objectId===t?.id),image=this.cache.get(c?.id);if(image){r.save();r.globalAlpha=.55;r.drawImage(image,-w*.04+Math.sin(time/15)*w*.02,-h*.05,w*1.1,h*1.1);r.restore();}r.fillStyle='#e5f2dd';r.font=`${w*.019}px monospace`;r.fillText('DEMO / SYNTHETIC TRAJECTORY',w*.035,h*.93);}
 if(s.background==='ORIGINAL')v.drawImage(this.real,0,0);else{v.strokeStyle='#27362f';v.lineWidth=1;for(let y=h*.58;y<h;y+=h*.06){v.beginPath();v.moveTo(0,y);v.lineTo(w,y);v.stroke();}for(let x=-w;x<w*2;x+=w*.15){v.beginPath();v.moveTo(w/2,h*.48);v.lineTo(x,h);v.stroke();}}
 const tracks=[...project.tracks].sort((a,b)=>{const x=boxAt(a,time),y=boxAt(b,time);return(x?x[2]*x[3]:0)-(y?y[2]*y[3]:0);});let index=0;
 for(const t of tracks){const b=boxAt(t,time);if(!b)continue;const [x,y,bw,bh]=[b[0]*w,b[1]*h,b[2]*w,b[3]*h];let mix=1;if(oldWorld&&s.transition!=='CUT'&&s.transitionTime>0){const delay=s.transition==='SPATIAL'?index/Math.max(1,tracks.length)*s.transitionTime*.65:0;mix=clamp((transitionAge-delay)/(s.transitionTime*(s.transition==='SPATIAL'?.35:1)));}index++;
 const draw=(id,alpha)=>{const image=this.cache.get(id);if(!image||alpha<=0)return;o.save();o.globalAlpha=alpha;o.fillStyle='#152221';o.fillRect(x,y,bw,bh);const aspect=image.width/image.height,desired=bw/bh;let sx=0,sy=0,sw=image.width,sh=image.height;if(aspect>desired){sw=sh*desired;sx=(image.width-sw)/2;}else{sh=sw/desired;sy=(image.height-sh)/2;}o.drawImage(image,sx,sy,sw,sh,x,y,bw,bh);o.strokeStyle='#d4ff7c';o.lineWidth=Math.max(1,w/1200);o.strokeRect(x,y,bw,bh);o.restore();};
 // Opaque base + overlaid new frame gives a true crossfade without a dark midpoint.
 if(mix<1)draw(oldWorld[t.id],1);draw(world[t.id],mix);if(project.source==='demo'){r.strokeStyle='#c1d4bd77';r.strokeRect(x,y,bw,bh);}}
 const fx=effectiveFX(s,loop,time);let objects=this.objects;if(s.fxTarget==='OBJECTS')objects=this.effects[2].apply(objects,fx,dt,s.echoDecay);v.drawImage(objects,0,0,w,h);let real=this.real,virtual=this.virtual;if(['REAL','BOTH'].includes(s.fxTarget))real=this.effects[0].apply(real,fx,dt,s.echoDecay);if(['VIRTUAL','BOTH'].includes(s.fxTarget))virtual=this.effects[1].apply(virtual,fx,dt,s.echoDecay);const ctx=this.ctx;ctx.clearRect(0,0,w,h);let view=s.view==='SWITCH'?(Math.floor(time/8)%2?'PARALLEL':'MIRROR'):s.view;if(view==='REAL')ctx.drawImage(real,0,0,w,h);if(view==='MIRROR'){ctx.save();ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(virtual,0,0,w,h);ctx.restore();}if(view==='PARALLEL'){ctx.drawImage(real,0,0,w/2,h);ctx.drawImage(virtual,w/2,0,w/2,h);ctx.fillStyle='#d4ff7c';ctx.fillRect(w/2-1,0,2,h);}if(view==='SPLIT'){ctx.drawImage(real,0,0,w,h);ctx.save();ctx.beginPath();ctx.rect(w/2,0,w/2,h);ctx.clip();ctx.drawImage(virtual,0,0,w,h);ctx.restore();ctx.fillStyle='#d4ff7c';ctx.fillRect(w/2-1,0,2,h);}return fx;}
}
