import {searchable} from './core.js';
export function features(image){const c=document.createElement('canvas');c.width=16;c.height=16;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,16,16);const pixels=ctx.getImageData(0,0,16,16).data;const h=Array(15).fill(0);for(let i=0;i<pixels.length;i+=4){for(let k=0;k<3;k++)h[k*4+Math.min(3,Math.floor(pixels[i+k]/64))]+=1/256;const l=(pixels[i]+pixels[i+1]+pixels[i+2])/765;h[12]+=l/256;if(i>=4)h[13]+=Math.abs(pixels[i]-pixels[i-4])/255/256;}h[14]=(image.naturalWidth||image.width)/(image.naturalHeight||image.height);return h;}
export function similarity(a,b){if(!a||!b)return null;let color=0;for(let i=0;i<12;i++)color+=Math.min(a[i],b[i]);return Math.max(0,Math.min(1,.7*color/3+.15*(1-Math.min(1,Math.abs(a[13]-b[13])*4))+.15*Math.min(a[14],b[14])/Math.max(a[14],b[14])));}
export async function loadImage(url){const img=new Image();img.crossOrigin='anonymous';img.src=url;await Promise.race([img.decode(),new Promise((_,reject)=>setTimeout(()=>reject(Error('画像の読み込みがタイムアウトしました')),15000))]);return img;}
const plain=s=>String(s||'').replace(/<[^>]*>/g,'').replace(/&[^;]+;/g,' ').trim();
export class CommonsProvider{
 async search(track,keyword=track.category,signal){if(!searchable(track.category)||!searchable(keyword))throw Error('人物・顔・ナンバープレートは検索対象外です');const params=new URLSearchParams({action:'query',generator:'search',gsrsearch:`${keyword.slice(0,160)} filetype:bitmap`,gsrnamespace:'6',gsrlimit:'12',prop:'imageinfo',iiprop:'url|extmetadata',iiurlwidth:'640',format:'json',origin:'*'});const response=await fetch(`https://commons.wikimedia.org/w/api.php?${params}`,{signal});if(!response.ok)throw Error(`画像検索エラー (${response.status})`);const data=await response.json();if(data.error)throw Error(data.error.info);return Object.values(data.query?.pages||{}).flatMap(p=>{const i=p.imageinfo?.[0];if(!i)return[];const m=i.extmetadata||{};return[{objectId:track.id,id:`commons-${p.pageid}-${track.id}`,url:i.thumburl||i.url,sourceUrl:i.descriptionurl,license:plain(m.LicenseShortName?.value)||'権利情報不明',licenseUrl:m.LicenseUrl?.value||'',author:plain(m.Artist?.value),attribution:plain(m.Credit?.value),keyword,features:null,similarity:null,retrievedAt:new Date().toISOString(),provider:'Wikimedia Commons',themes:[],excluded:false}];});}
}
export async function enrich(candidates,track,cache,onProgress=()=>{}){for(let i=0;i<candidates.length;i++){const c=candidates[i];try{const img=await loadImage(c.url);cache.set(c.id,img);c.features=features(img);c.similarity=similarity(track.features,c.features);c.loadError=false;}catch{c.loadError=true;}onProgress(i+1,candidates.length);}return candidates;}
